version: '3.8'

services:
  # PostgreSQL database for local development
  postgres:
    image: postgres:15-alpine
    container_name: aura-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: aura_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - aura-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aura_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional, with fallback to memory)
  redis:
    image: redis:7-alpine
    container_name: aura-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aura-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  aura-dev:
    driver: bridge
    name: aura-development